FROM python:3.13.3
WORKDIR /App1
COPY  requirements.auth.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r requirements.auth.txt 
COPY  . .
EXPOSE 10002
ENV Mydev=userautheticationDev
CMD ["python","-m","streamlit","run","./usersauthetication.py","--server.address","0.0.0.0","--server.port","10002"]