FROM python:3.13.3
WORKDIR /App2
COPY  requirements.back.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r requirements.back.txt 
COPY  . .
EXPOSE 10003
ENV Mydev=uservalidationback
CMD ["python", "-m", "uvicorn", "uservalidations:app", "--host", "0.0.0.0", "--port", "10003"]